Repository dnd-side-project/dnd-7th-2-android, pull requests merged in 2022-08, with the labels that each got.

#9 Home 구현(임시)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/niceteam/MainApplication.kt
  app/src/main/java/com/dnd/niceteam/base/BaseActivity.kt
  app/src/main/java/com/dnd/niceteam/base/BaseFragment.kt
  app/src/main/java/com/dnd/niceteam/ui/MainActivity.kt
  app/src/main/java/com/dnd/niceteam/ui/home/ProgressTeampleItemDecoration.kt
  app/src/main/java/com/dnd/niceteam/ui/home/adapter/ProgressTeampleAdapter.kt
  app/src/main/java/com/dnd/niceteam/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd/niceteam/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/dnd/niceteam/util/BindingAdapter.kt
  app/src/main/java/com/dnd/niceteam/util/Utils.kt
  app/src/main/res/drawable/bg_circle_dark_gray.xml
  app/src/main/res/drawable/bg_dark_purple_bottom_radius_15dp.xml
  app/src/main/res/drawable/bg_item_progess_teample.xml
  app/src/main/res/drawable/bg_light_green_15dp.xml
  app/src/main/res/drawable/bg_purple_bottom_radius_15dp.xml
  app/src/main/res/drawable/btn_light_green_10dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_progress_teample.xml
  app/src/main/res/layout/layout_home_content.xml
  app/src/main/res/layout/layout_home_top_banner.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, ui, style, chore

#10 네이밍 변경
  app/src/main/java/com/dnd/niceteam/ui/home/adapter/ProgressTeampleAdapter.kt
  app/src/main/res/layout/fragment_home.xml
Labels: style

#12 커스텀 앱바
  app/src/main/java/com/dnd/niceteam/ui/common/TeamGooAppBar.kt
  app/src/main/res/layout/view_appbar.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: ui

#14 시작화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/niceteam/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/bg_splash_screen.xml
  app/src/main/res/drawable/ic_teamgoo_logo.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: ui

#16 바텀네비게이션 구성
  app/src/main/java/com/dnd/niceteam/ui/MainActivity.kt
  app/src/main/java/com/dnd/niceteam/ui/lecture/view/LectureFragment.kt
  app/src/main/java/com/dnd/niceteam/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/dnd/niceteam/ui/side/view/SideFragment.kt
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_lecture.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_side.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_lecture.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_side.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/navigation/bottom_navigation.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: feature

#20 커스텀 앱바 수정
  app/src/main/java/com/dnd/niceteam/ui/common/TeamGooAppBar.kt
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_flag.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_home_top_banner.xml
  app/src/main/res/layout/view_appbar.xml
  app/src/main/res/values/attrs.xml
Labels: ui

#25 feat: Custom ItemDecoration
  app/src/main/java/com/dnd/niceteam/ui/common/TeamGooDecoration.kt
  app/src/main/java/com/dnd/niceteam/util/BindingAdapter.kt
Labels: feature

#33 북마크 프로토타입 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd/niceteam/ui/home/bookmark/BookmarkItemDecoration.kt
  app/src/main/java/com/dnd/niceteam/ui/home/bookmark/adapter/BookmarkAdapter.kt
  app/src/main/java/com/dnd/niceteam/ui/home/bookmark/view/BookmarkActivity.kt
  app/src/main/java/com/dnd/niceteam/ui/home/bookmark/viewmodel/BookmarkViewModel.kt
  app/src/main/java/com/dnd/niceteam/ui/home/homescreen/view/HomeFragment.kt
  app/src/main/res/drawable/bg_blue_bottom_16dp.xml
  app/src/main/res/drawable/bg_dark_purple_bottom_15dp.xml
  app/src/main/res/drawable/bg_green_16dp.xml
  app/src/main/res/drawable/bg_purple_16dp.xml
  app/src/main/res/drawable/bg_purple_bottom_16dp.xml
  app/src/main/res/drawable/bg_white_stroke_gray_12dp.xml
  app/src/main/res/drawable/bg_white_stroke_purple_6dp.xml
  app/src/main/res/drawable/btn_white_stroke_purple_15dp.xml
  app/src/main/res/drawable/ic_arrow_right_light_gray.xml
  app/src/main/res/drawable/ic_bookmark_14dp.xml
  app/src/main/res/drawable/ic_bookmark_15dp.xml
  app/src/main/res/drawable/ic_bookmark_purple.xml
  app/src/main/res/drawable/ic_team_light_gray.xml
  app/src/main/res/drawable/selector_chip_stroke.xml
  app/src/main/res/drawable/selector_chip_text.xml
  app/src/main/res/drawable/tab_indicator_black_3dp.xml
  app/src/main/res/layout/activity_bookmark.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/item_bookmark.xml
  app/src/main/res/layout/item_progress_teample.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, ui, style, chore
